### ISSUE TITLE
Can't see bottom of expanded menu on mobile

### ISSUE THREAD

**Issue by kalafut** [ghostty-org/website#153]
Using Safari on iPhone 14:

1. Visit the docs
2. Expand hamburger menu
3. Expand Help
4. I can tell there are more items in the help list, but the menu/page won't scroll.

**Comment by BrandonRomano** [comment]
Good catch; I think I know what's going on here!

**Comment by BrandonRomano** [comment]
@kalafut would you mind giving this another spin to see if it's fixed for you?  I was able to reproduce on my iPhone 15 in Safari and was able to find a fix. I don't have an iPhone 14 to test on; and want to make sure it's fixed with your browser / setup.

Please re-open if the issue is still observed.

Thank you for the report 🙇

**Comment by kalafut** [comment]
Looks good on my end too. Thanks for the quick fix!

- Jim
